language: scala

scala:
   - 2.13.1

jdk:
   - oraclejdk11

env:
  - NODE_VERSION="12.6.0"

before_install:
  - nvm install $NODE_VERSION

cache:
   directories:
      - $HOME/.sbt/1.0/dependency
      - $HOME/.sbt/boot/scala*
      - $HOME/.sbt/launchers
      - $HOME/.m2
      - $HOME/.ivy2/cache
      - $HOME/.coursier
      - $HOME/.nvm

before_cache:
   - find $HOME/.sbt -name "*.lock" -type f -delete
   - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
   - rm -rf $HOME/.ivy2/local

script:
   - sbt ++$TRAVIS_SCALA_VERSION testAnswers
   - npm install -g decktape
   - bin/gen-pdf.sh

deploy:
   provider: pages
   local_dir: docs/
   skip_cleanup: true
   github_token: $GH_TOKEN
   on:
      branch: master
      condition: $TRAVIS_PULL_REQUEST="false"
